title: "Hello, Neovim！"
summary: "vimvimする"
topics: ["neovim", "lazyvim"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
toc_depth: 1
chapters:
  - Neovimって？
  - 既に設定している人向け マルチプロファイル
  - スターターを触ってNeovimを試してみよう LazyVim
  - パッケージ管理マネージャーを使ってみよう lazy.nvim
  - 基本設定
  - ファイラーを導入してファイル管理をいい感じに
  - ファジーにファインドするプラグインを設定しよう
